services:
  ros:
    image: yolo_ros
    container_name: ros
    network_mode: host
    privileged: true
    devices:
      - "/dev/video0:/dev/usb_cam"
      - "/dev/input/js0:/dev/input/js0" # map joystick device
      - "/dev/hidraw0:/dev/hidraw0" # map HID device
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    command: tail -f /dev/null
