services:
  ros:
    image: yolo_ros
    container_name: ros
    network_mode: host
    privileged: true
    devices:
      #- "/dev/video0:/dev/usb_cam"
      - "/dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_4C48AFAF-video-index0:/dev/usb_cam" # Jamie's webcam by USB ID
      - "/dev/input/js0:/dev/input/js0" # map joystick device
      - "/dev/hidraw0:/dev/hidraw0" # map HID device
    volumes:
      - ~/ros2_dice_ws:/ros2_ws
      - ~/yolo_models:/yolo_models
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    command: tail -f /dev/null
